spring:
  security:
    oauth2:
      client:
        registration:
          github:
            provider: github
            client-id: c910e8fb3585665b4b87
            client-secret: 52cf40bae8ab4acd5afcd36bb830a423fb0b0906
            scope:
              - email
security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess
      registered-redirect-uri: http://localhost:8081/client/login
      auto-approve-scopes: user_info
      scope: user_info
      authorized-grant-types: authorization_code

logging.level.org.springframework: debug
server.servlet.session.cookie.name: auth
