#http://localhost:8080/login/oauth2/code/github
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 856085966769-bjt5l19o7fritg5io7lj63f2uj39p9ov.apps.googleusercontent.com
            client-secret: yzETZtPqb_eG5kIClkoITupp
            scope:
              - email
          github:
            provider: github
            client-id: c910e8fb3585665b4b87
            client-secret: 52cf40bae8ab4acd5afcd36bb830a423fb0b0906
            scope:
              - email
          facebook:
            provider: facebook
            client-id: 2198380310473302
            client-secret: 3bf2aa7540d53c9bf2ab2016e453ee35
            scope:
              - email
logging.level.org.springframework.security: debug
