spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 856085966769-bjt5l19o7fritg5io7lj63f2uj39p9ov.apps.googleusercontent.com
            client-secret: yzETZtPqb_eG5kIClkoITupp
            scope:
              - email
          github:
            provider: github
            client-id: c910e8fb3585665b4b87
            client-secret: 52cf40bae8ab4acd5afcd36bb830a423fb0b0906
            scope:
              - email